  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About Me"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "My Projects"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"
